package win32api

//go:generate go run golang.org/x/tools/cmd/stringer -output win32api_const_string.go -type MessageId
const (
	AnsiCharset                                          = 0                     // constant.int64Val
	AntialiasedQuality                                   = 4                     // constant.int64Val
	ArabicCharset                                        = 178                   // constant.int64Val
	BalticCharset                                        = 186                   // constant.int64Val
	Bs3state                                             = 5                     // constant.int64Val
	BsAuto3state                                         = 6                     // constant.int64Val
	BsAutocheckbox                                       = 3                     // constant.int64Val
	BsAutoradiobutton                                    = 9                     // constant.int64Val
	BsBitmap                                             = 128                   // constant.int64Val
	BsBottom                                             = 2048                  // constant.int64Val
	BsCenter                                             = 768                   // constant.int64Val
	BsCheckbox                                           = 2                     // constant.int64Val
	BsDefpushbutton                                      = 1                     // constant.int64Val
	BsFlat                                               = 32768                 // constant.int64Val
	BsGroupbox                                           = 7                     // constant.int64Val
	BsIcon                                               = 64                    // constant.int64Val
	BsLeft                                               = 256                   // constant.int64Val
	BsLefttext                                           = 32                    // constant.int64Val
	BsMultiline                                          = 8192                  // constant.int64Val
	BsNotify                                             = 16384                 // constant.int64Val
	BsOwnerdraw                                          = 11                    // constant.int64Val
	BsPushbox                                            = 10                    // constant.int64Val
	BsPushbutton                                         = 0                     // constant.int64Val
	BsPushlike                                           = 4096                  // constant.int64Val
	BsRadiobutton                                        = 4                     // constant.int64Val
	BsRight                                              = 512                   // constant.int64Val
	BsRightbutton                                        = 32                    // constant.int64Val
	BsText                                               = 0                     // constant.int64Val
	BsTop                                                = 1024                  // constant.int64Val
	BsTypemask                                           = 15                    // constant.int64Val
	BsUserbutton                                         = 8                     // constant.int64Val
	BsVcenter                                            = 3072                  // constant.int64Val
	Chinesebig5Charset                                   = 136                   // constant.int64Val
	CleartypeNaturalQuality                              = 6                     // constant.int64Val
	CleartypeQuality                                     = 5                     // constant.int64Val
	ClipCharacterPrecis                                  = 1                     // constant.int64Val
	ClipDefaultPrecis                                    = 0                     // constant.int64Val
	ClipDfaDisable                                       = 64                    // constant.int64Val
	ClipEmbedded                                         = 128                   // constant.int64Val
	ClipLhAngles                                         = 16                    // constant.int64Val
	ClipMask                                             = 15                    // constant.int64Val
	ClipStrokePrecis                                     = 2                     // constant.int64Val
	ClipToPath                                           = 4097                  // constant.int64Val
	ClipTtAlways                                         = 32                    // constant.int64Val
	Colorokstring                                        = "commdlg_ColorOK"     // *constant.stringVal
	CsBytealignclient                                    = 4096                  // constant.int64Val
	CsBytealignwindow                                    = 8192                  // constant.int64Val
	CsClassdc                                            = 64                    // constant.int64Val
	CsDblclks                                            = 8                     // constant.int64Val
	CsDropshadow                                         = 131072                // constant.int64Val
	CsGlobalclass                                        = 16384                 // constant.int64Val
	CsHredraw                                            = 2                     // constant.int64Val
	CsIme                                                = 65536                 // constant.int64Val
	CsNoclose                                            = 512                   // constant.int64Val
	CsOwndc                                              = 32                    // constant.int64Val
	CsParentdc                                           = 128                   // constant.int64Val
	CsSavebits                                           = 2048                  // constant.int64Val
	CsVredraw                                            = 1                     // constant.int64Val
	CsidlAdmintools                                      = 48                    // constant.int64Val
	CsidlAltstartup                                      = 29                    // constant.int64Val
	CsidlAppdata                                         = 26                    // constant.int64Val
	CsidlBitbucket                                       = 10                    // constant.int64Val
	CsidlCdburnArea                                      = 59                    // constant.int64Val
	CsidlCommonAdmintools                                = 47                    // constant.int64Val
	CsidlCommonAltstartup                                = 30                    // constant.int64Val
	CsidlCommonAppdata                                   = 35                    // constant.int64Val
	CsidlCommonDesktopdirectory                          = 25                    // constant.int64Val
	CsidlCommonDocuments                                 = 46                    // constant.int64Val
	CsidlCommonFavorites                                 = 31                    // constant.int64Val
	CsidlCommonMusic                                     = 53                    // constant.int64Val
	CsidlCommonOemLinks                                  = 58                    // constant.int64Val
	CsidlCommonPictures                                  = 54                    // constant.int64Val
	CsidlCommonPrograms                                  = 23                    // constant.int64Val
	CsidlCommonStartmenu                                 = 22                    // constant.int64Val
	CsidlCommonStartup                                   = 24                    // constant.int64Val
	CsidlCommonTemplates                                 = 45                    // constant.int64Val
	CsidlCommonVideo                                     = 55                    // constant.int64Val
	CsidlComputersnearme                                 = 61                    // constant.int64Val
	CsidlConnections                                     = 49                    // constant.int64Val
	CsidlControls                                        = 3                     // constant.int64Val
	CsidlCookies                                         = 33                    // constant.int64Val
	CsidlDesktop                                         = 0                     // constant.int64Val
	CsidlDesktopdirectory                                = 16                    // constant.int64Val
	CsidlDrives                                          = 17                    // constant.int64Val
	CsidlFavorites                                       = 6                     // constant.int64Val
	CsidlFlagCreate                                      = 32768                 // constant.int64Val
	CsidlFlagDontUnexpand                                = 8192                  // constant.int64Val
	CsidlFlagDontVerify                                  = 16384                 // constant.int64Val
	CsidlFlagMask                                        = 65280                 // constant.int64Val
	CsidlFlagNoAlias                                     = 4096                  // constant.int64Val
	CsidlFlagPerUserInit                                 = 2048                  // constant.int64Val
	CsidlFonts                                           = 20                    // constant.int64Val
	CsidlHistory                                         = 34                    // constant.int64Val
	CsidlInternet                                        = 1                     // constant.int64Val
	CsidlInternetCache                                   = 32                    // constant.int64Val
	CsidlLocalAppdata                                    = 28                    // constant.int64Val
	CsidlMydocuments                                     = 5                     // constant.int64Val
	CsidlMymusic                                         = 13                    // constant.int64Val
	CsidlMypictures                                      = 39                    // constant.int64Val
	CsidlMyvideo                                         = 14                    // constant.int64Val
	CsidlNethood                                         = 19                    // constant.int64Val
	CsidlNetwork                                         = 18                    // constant.int64Val
	CsidlPersonal                                        = 5                     // constant.int64Val
	CsidlPrinters                                        = 4                     // constant.int64Val
	CsidlPrinthood                                       = 27                    // constant.int64Val
	CsidlProfile                                         = 40                    // constant.int64Val
	CsidlProgramFiles                                    = 38                    // constant.int64Val
	CsidlProgramFilesCommon                              = 43                    // constant.int64Val
	CsidlProgramFilesCommonx86                           = 44                    // constant.int64Val
	CsidlProgramFilesx86                                 = 42                    // constant.int64Val
	CsidlPrograms                                        = 2                     // constant.int64Val
	CsidlRecent                                          = 8                     // constant.int64Val
	CsidlResources                                       = 56                    // constant.int64Val
	CsidlResourcesLocalized                              = 57                    // constant.int64Val
	CsidlSendto                                          = 9                     // constant.int64Val
	CsidlStartmenu                                       = 11                    // constant.int64Val
	CsidlStartup                                         = 7                     // constant.int64Val
	CsidlSystem                                          = 37                    // constant.int64Val
	CsidlSystemx86                                       = 41                    // constant.int64Val
	CsidlTemplates                                       = 21                    // constant.int64Val
	CsidlWindows                                         = 36                    // constant.int64Val
	CwUsedefault                                         = -2147483648           // constant.int64Val
	DefaultCharset                                       = 1                     // constant.int64Val
	DefaultPitch                                         = 0                     // constant.int64Val
	DefaultQuality                                       = 0                     // constant.int64Val
	DraftQuality                                         = 1                     // constant.int64Val
	EasteuropeCharset                                    = 238                   // constant.int64Val
	EmCanundo                                            = 198                   // constant.int64Val
	EmCharfrompos                                        = 215                   // constant.int64Val
	EmEmptyundobuffer                                    = 205                   // constant.int64Val
	EmFmtlines                                           = 200                   // constant.int64Val
	EmGetfirstvisibleline                                = 206                   // constant.int64Val
	EmGethandle                                          = 189                   // constant.int64Val
	EmGetimestatus                                       = 217                   // constant.int64Val
	EmGetlimittext                                       = 213                   // constant.int64Val
	EmGetline                                            = 196                   // constant.int64Val
	EmGetlinecount                                       = 186                   // constant.int64Val
	EmGetmargins                                         = 212                   // constant.int64Val
	EmGetmodify                                          = 184                   // constant.int64Val
	EmGetpasswordchar                                    = 210                   // constant.int64Val
	EmGetrect                                            = 178                   // constant.int64Val
	EmGetsel                                             = 176                   // constant.int64Val
	EmGetthumb                                           = 190                   // constant.int64Val
	EmGetwordbreakproc                                   = 209                   // constant.int64Val
	EmLimittext                                          = 197                   // constant.int64Val
	EmLinefromchar                                       = 201                   // constant.int64Val
	EmLineindex                                          = 187                   // constant.int64Val
	EmLinelength                                         = 193                   // constant.int64Val
	EmLinescroll                                         = 182                   // constant.int64Val
	EmPosfromchar                                        = 214                   // constant.int64Val
	EmReplacesel                                         = 194                   // constant.int64Val
	EmScroll                                             = 181                   // constant.int64Val
	EmScrollcaret                                        = 183                   // constant.int64Val
	EmSethandle                                          = 188                   // constant.int64Val
	EmSetimestatus                                       = 216                   // constant.int64Val
	EmSetlimittext                                       = 197                   // constant.int64Val
	EmSetmargins                                         = 211                   // constant.int64Val
	EmSetmodify                                          = 185                   // constant.int64Val
	EmSetpasswordchar                                    = 204                   // constant.int64Val
	EmSetreadonly                                        = 207                   // constant.int64Val
	EmSetrect                                            = 179                   // constant.int64Val
	EmSetrectnp                                          = 180                   // constant.int64Val
	EmSetsel                                             = 177                   // constant.int64Val
	EmSettabstops                                        = 203                   // constant.int64Val
	EmSetwordbreakproc                                   = 208                   // constant.int64Val
	EmUndo                                               = 199                   // constant.int64Val
	EsAutohscroll                                        = 128                   // constant.int64Val
	EsAutovscroll                                        = 64                    // constant.int64Val
	EsCenter                                             = 1                     // constant.int64Val
	EsLeft                                               = 0                     // constant.int64Val
	EsLowercase                                          = 16                    // constant.int64Val
	EsMultiline                                          = 4                     // constant.int64Val
	EsNohidesel                                          = 256                   // constant.int64Val
	EsNumber                                             = 8192                  // constant.int64Val
	EsOemconvert                                         = 1024                  // constant.int64Val
	EsPassword                                           = 32                    // constant.int64Val
	EsReadonly                                           = 2048                  // constant.int64Val
	EsRight                                              = 2                     // constant.int64Val
	EsUppercase                                          = 8                     // constant.int64Val
	EsWantreturn                                         = 4096                  // constant.int64Val
	False                                                = 0                     // constant.int64Val
	FfDecorative                                         = 80                    // constant.int64Val
	FfDontcare                                           = 0                     // constant.int64Val
	FfModern                                             = 48                    // constant.int64Val
	FfRoman                                              = 16                    // constant.int64Val
	FfScript                                             = 64                    // constant.int64Val
	FfSwiss                                              = 32                    // constant.int64Val
	Fileokstring                                         = "commdlg_FileNameOK"  // *constant.stringVal
	Findmsgstring                                        = "commdlg_FindReplace" // *constant.stringVal
	FixedPitch                                           = 1                     // constant.int64Val
	FrDialogterm                                         = 64                    // constant.int64Val
	FrDown                                               = 1                     // constant.int64Val
	FrEnablehook                                         = 256                   // constant.int64Val
	FrEnabletemplate                                     = 512                   // constant.int64Val
	FrEnabletemplatehandle                               = 8192                  // constant.int64Val
	FrFindnext                                           = 8                     // constant.int64Val
	FrHidematchcase                                      = 32768                 // constant.int64Val
	FrHideupdown                                         = 16384                 // constant.int64Val
	FrHidewholeword                                      = 65536                 // constant.int64Val
	FrMatchalefhamza                                     = 2147483648            // constant.int64Val
	FrMatchcase                                          = 4                     // constant.int64Val
	FrMatchdiac                                          = 536870912             // constant.int64Val
	FrMatchkashida                                       = 1073741824            // constant.int64Val
	FrNomatchcase                                        = 2048                  // constant.int64Val
	FrNoupdown                                           = 1024                  // constant.int64Val
	FrNowholeword                                        = 4096                  // constant.int64Val
	FrRaw                                                = 131072                // constant.int64Val
	FrReplace                                            = 16                    // constant.int64Val
	FrReplaceall                                         = 32                    // constant.int64Val
	FrShowhelp                                           = 128                   // constant.int64Val
	FrWholeword                                          = 2                     // constant.int64Val
	FwBlack                                              = 900                   // constant.int64Val
	FwBold                                               = 700                   // constant.int64Val
	FwDemibold                                           = 600                   // constant.int64Val
	FwDontcare                                           = 0                     // constant.int64Val
	FwExtrabold                                          = 800                   // constant.int64Val
	FwExtralight                                         = 200                   // constant.int64Val
	FwHeavy                                              = 900                   // constant.int64Val
	FwLight                                              = 300                   // constant.int64Val
	FwMedium                                             = 500                   // constant.int64Val
	FwNormal                                             = 400                   // constant.int64Val
	FwRegular                                            = 400                   // constant.int64Val
	FwSemibold                                           = 600                   // constant.int64Val
	FwThin                                               = 100                   // constant.int64Val
	FwUltrabold                                          = 800                   // constant.int64Val
	FwUltralight                                         = 200                   // constant.int64Val
	Gb2312Charset                                        = 134                   // constant.int64Val
	GreekCharset                                         = 161                   // constant.int64Val
	GwlExstyle                                           = -20                   // constant.int64Val
	GwlId                                                = -12                   // constant.int64Val
	GwlStyle                                             = -16                   // constant.int64Val
	GwlpHinstance                                        = -6                    // constant.int64Val
	GwlpHwndparent                                       = -8                    // constant.int64Val
	GwlpId                                               = -12                   // constant.int64Val
	GwlpUserdata                                         = -21                   // constant.int64Val
	GwlpWndproc                                          = -4                    // constant.int64Val
	HangeulCharset                                       = 129                   // constant.int64Val
	HangulCharset                                        = 129                   // constant.int64Val
	HebrewCharset                                        = 177                   // constant.int64Val
	Helpmsgstring                                        = "commdlg_help"        // *constant.stringVal
	Htborder                                             = 18                    // constant.int64Val
	Htbottom                                             = 15                    // constant.int64Val
	Htbottomleft                                         = 16                    // constant.int64Val
	Htbottomright                                        = 17                    // constant.int64Val
	Htcaption                                            = 2                     // constant.int64Val
	Htclient                                             = 1                     // constant.int64Val
	Htclose                                              = 20                    // constant.int64Val
	Hterror                                              = -2                    // constant.int64Val
	Htgrowbox                                            = 4                     // constant.int64Val
	Hthelp                                               = 21                    // constant.int64Val
	Hthscroll                                            = 6                     // constant.int64Val
	Htleft                                               = 10                    // constant.int64Val
	Htmaxbutton                                          = 9                     // constant.int64Val
	Htmenu                                               = 5                     // constant.int64Val
	Htminbutton                                          = 8                     // constant.int64Val
	Htnowhere                                            = 0                     // constant.int64Val
	Htobject                                             = 19                    // constant.int64Val
	Htreduce                                             = 8                     // constant.int64Val
	Htright                                              = 11                    // constant.int64Val
	Htsize                                               = 4                     // constant.int64Val
	Htsizefirst                                          = 10                    // constant.int64Val
	Htsizelast                                           = 17                    // constant.int64Val
	Htsysmenu                                            = 3                     // constant.int64Val
	Httop                                                = 12                    // constant.int64Val
	Httopleft                                            = 13                    // constant.int64Val
	Httopright                                           = 14                    // constant.int64Val
	Httransparent                                        = -1                    // constant.int64Val
	Htvscroll                                            = 7                     // constant.int64Val
	Htzoom                                               = 9                     // constant.int64Val
	Idabort                                              = 3                     // constant.int64Val
	IdcAppstarting                                       = 32650                 // constant.int64Val
	IdcArrow                                             = 32512                 // constant.int64Val
	IdcCross                                             = 32515                 // constant.int64Val
	IdcHand                                              = 32649                 // constant.int64Val
	IdcHelp                                              = 32651                 // constant.int64Val
	IdcIbeam                                             = 32513                 // constant.int64Val
	IdcIcon                                              = 32641                 // constant.int64Val
	IdcMissing32647                                      = 32647                 // constant.int64Val
	IdcNo                                                = 32648                 // constant.int64Val
	IdcSize                                              = 32640                 // constant.int64Val
	IdcSizeall                                           = 32646                 // constant.int64Val
	IdcSizenesw                                          = 32643                 // constant.int64Val
	IdcSizens                                            = 32645                 // constant.int64Val
	IdcSizenwse                                          = 32642                 // constant.int64Val
	IdcSizewe                                            = 32644                 // constant.int64Val
	IdcUparrow                                           = 32516                 // constant.int64Val
	IdcWait                                              = 32514                 // constant.int64Val
	Idcancel                                             = 2                     // constant.int64Val
	Idclose                                              = 8                     // constant.int64Val
	Idcontinue                                           = 11                    // constant.int64Val
	Idhelp                                               = 9                     // constant.int64Val
	Idignore                                             = 5                     // constant.int64Val
	Idno                                                 = 7                     // constant.int64Val
	Idok                                                 = 1                     // constant.int64Val
	Idretry                                              = 4                     // constant.int64Val
	Idtimeout                                            = 32000                 // constant.int64Val
	Idtryagain                                           = 10                    // constant.int64Val
	Idyes                                                = 6                     // constant.int64Val
	JohabCharset                                         = 130                   // constant.int64Val
	KfAltdown                                            = 8192                  // constant.int64Val
	KfDlgmode                                            = 2048                  // constant.int64Val
	KfExtended                                           = 256                   // constant.int64Val
	KfFlagAliasOnly                  KnownFolderFlag     = 2147483648
	KfFlagCreate                     KnownFolderFlag     = 32768
	KfFlagDefault                    KnownFolderFlag     = 0
	KfFlagDefaultPath                KnownFolderFlag     = 1024
	KfFlagDontUnexpand               KnownFolderFlag     = 8192
	KfFlagDontVerify                 KnownFolderFlag     = 16384
	KfFlagInit                       KnownFolderFlag     = 2048
	KfFlagNoAlias                    KnownFolderFlag     = 4096
	KfFlagNoAppcontainerRedirection  KnownFolderFlag     = 65536
	KfFlagNotParentRelative          KnownFolderFlag     = 512
	KfFlagSimpleIdlist               KnownFolderFlag     = 256
	KfMenumode                                           = 4096                         // constant.int64Val
	KfRepeat                                             = 16384                        // constant.int64Val
	KfUp                                                 = 32768                        // constant.int64Val
	Lbselchstring                                        = "commdlg_LBSelChangedNotify" // *constant.stringVal
	Logpixelsx                                           = 88                           // constant.int64Val
	Logpixelsy                                           = 90                           // constant.int64Val
	MacCharset                                           = 77                           // constant.int64Val
	MfAppend                                             = 256                          // constant.int64Val
	MfBitmap                                             = 4                            // constant.int64Val
	MfBycommand                                          = 0                            // constant.int64Val
	MfByposition                                         = 1024                         // constant.int64Val
	MfChange                                             = 128                          // constant.int64Val
	MfChecked                                            = 8                            // constant.int64Val
	MfDefault                                            = 4096                         // constant.int64Val
	MfDelete                                             = 512                          // constant.int64Val
	MfDisabled                                           = 2                            // constant.int64Val
	MfEnabled                                            = 0                            // constant.int64Val
	MfEnd                                                = 128                          // constant.int64Val
	MfGrayed                                             = 1                            // constant.int64Val
	MfHelp                                               = 16384                        // constant.int64Val
	MfHilite                                             = 128                          // constant.int64Val
	MfInsert                                             = 0                            // constant.int64Val
	MfMenubarbreak                                       = 32                           // constant.int64Val
	MfMenubreak                                          = 64                           // constant.int64Val
	MfMouseselect                                        = 32768                        // constant.int64Val
	MfOwnerdraw                                          = 256                          // constant.int64Val
	MfPopup                                              = 16                           // constant.int64Val
	MfRemove                                             = 4096                         // constant.int64Val
	MfRightjustify                                       = 16384                        // constant.int64Val
	MfSeparator                                          = 2048                         // constant.int64Val
	MfString                                             = 0                            // constant.int64Val
	MfSysmenu                                            = 8192                         // constant.int64Val
	MfUnchecked                                          = 0                            // constant.int64Val
	MfUnhilite                                           = 0                            // constant.int64Val
	MfUsecheckbitmaps                                    = 512                          // constant.int64Val
	MkControl                                            = 8                            // constant.int64Val
	MkLbutton                                            = 1                            // constant.int64Val
	MkMbutton                                            = 16                           // constant.int64Val
	MkRbutton                                            = 2                            // constant.int64Val
	MkShift                                              = 4                            // constant.int64Val
	MkXbutton1                                           = 32                           // constant.int64Val
	MkXbutton2                                           = 64                           // constant.int64Val
	NonantialiasedQuality                                = 3                            // constant.int64Val
	ObjidAlert                                           = -10                          // constant.int64Val
	ObjidCaret                                           = -8                           // constant.int64Val
	ObjidClient                                          = -4                           // constant.int64Val
	ObjidCursor                                          = -9                           // constant.int64Val
	ObjidHscroll                                         = -6                           // constant.int64Val
	ObjidMenu                                            = -3                           // constant.int64Val
	ObjidNativeom                                        = -16                          // constant.int64Val
	ObjidQueryclassnameidx                               = -12                          // constant.int64Val
	ObjidSizegrip                                        = -7                           // constant.int64Val
	ObjidSound                                           = -11                          // constant.int64Val
	ObjidSysmenu                                         = -1                           // constant.int64Val
	ObjidTitlebar                                        = -2                           // constant.int64Val
	ObjidVscroll                                         = -5                           // constant.int64Val
	ObjidWindow                                          = 0                            // constant.int64Val
	OemCharset                                           = 255                          // constant.int64Val
	OutCharacterPrecis                                   = 2                            // constant.int64Val
	OutDefaultPrecis                                     = 0                            // constant.int64Val
	OutDevicePrecis                                      = 5                            // constant.int64Val
	OutOutlinePrecis                                     = 8                            // constant.int64Val
	OutPsOnlyPrecis                                      = 10                           // constant.int64Val
	OutRasterPrecis                                      = 6                            // constant.int64Val
	OutScreenOutlinePrecis                               = 9                            // constant.int64Val
	OutStringPrecis                                      = 1                            // constant.int64Val
	OutStrokePrecis                                      = 3                            // constant.int64Val
	OutTtOnlyPrecis                                      = 7                            // constant.int64Val
	OutTtPrecis                                          = 4                            // constant.int64Val
	PfdDepthDontcare                                     = 536870912                    // constant.int64Val
	PfdDirect3dAccelerated                               = 16384                        // constant.int64Val
	PfdDoublebuffer                                      = 1                            // constant.int64Val
	PfdDoublebufferDontcare                              = 1073741824                   // constant.int64Val
	PfdDrawToBitmap                                      = 8                            // constant.int64Val
	PfdDrawToWindow                                      = 4                            // constant.int64Val
	PfdGenericAccelerated                                = 4096                         // constant.int64Val
	PfdGenericFormat                                     = 64                           // constant.int64Val
	PfdMainPlane                                         = 0                            // constant.int64Val
	PfdNeedPalette                                       = 128                          // constant.int64Val
	PfdNeedSystemPalette                                 = 256                          // constant.int64Val
	PfdOverlayPlane                                      = 1                            // constant.int64Val
	PfdStereo                                            = 2                            // constant.int64Val
	PfdStereoDontcare                                    = 2147483648                   // constant.int64Val
	PfdSupportComposition                                = 32768                        // constant.int64Val
	PfdSupportDirectdraw                                 = 8192                         // constant.int64Val
	PfdSupportGdi                                        = 16                           // constant.int64Val
	PfdSupportOpengl                                     = 32                           // constant.int64Val
	PfdSwapCopy                                          = 1024                         // constant.int64Val
	PfdSwapExchange                                      = 512                          // constant.int64Val
	PfdSwapLayerBuffers                                  = 2048                         // constant.int64Val
	PfdTypeColorindex                                    = 1                            // constant.int64Val
	PfdTypeRgba                                          = 0                            // constant.int64Val
	PfdUnderlayPlane                                     = -1                           // constant.int64Val
	ProcessDpiUnaware                ProcessDpiAwareness = 0
	ProcessPerMonitorDpiAware        ProcessDpiAwareness = 2
	ProcessSystemDpiAware            ProcessDpiAwareness = 1
	ProofQuality                                         = 2                        // constant.int64Val
	RussianCharset                                       = 204                      // constant.int64Val
	SFalse                                               = 1                        // constant.int64Val
	SOk                                                  = 0                        // constant.int64Val
	Setrgbstring                                         = "commdlg_SetRGBColor"    // *constant.stringVal
	Sharevistring                                        = "commdlg_ShareViolation" // *constant.stringVal
	ShiftjisCharset                                      = 128                      // constant.int64Val
	SizeMaxhide                                          = 4                        // constant.int64Val
	SizeMaximized                                        = 2                        // constant.int64Val
	SizeMaxshow                                          = 3                        // constant.int64Val
	SizeMinimized                                        = 1                        // constant.int64Val
	SizeRestored                                         = 0                        // constant.int64Val
	SmArrange                                            = 56                       // constant.int64Val
	SmCaretblinkingenabled                               = 8194                     // constant.int64Val
	SmCleanboot                                          = 67                       // constant.int64Val
	SmCmetrics                                           = 97                       // constant.int64Val
	SmCmonitors                                          = 80                       // constant.int64Val
	SmCmousebuttons                                      = 43                       // constant.int64Val
	SmCxborder                                           = 5                        // constant.int64Val
	SmCxcursor                                           = 13                       // constant.int64Val
	SmCxdlgframe                                         = 7                        // constant.int64Val
	SmCxdoubleclk                                        = 36                       // constant.int64Val
	SmCxdrag                                             = 68                       // constant.int64Val
	SmCxedge                                             = 45                       // constant.int64Val
	SmCxfixedframe                                       = 7                        // constant.int64Val
	SmCxfocusborder                                      = 83                       // constant.int64Val
	SmCxframe                                            = 32                       // constant.int64Val
	SmCxfullscreen                                       = 16                       // constant.int64Val
	SmCxhscroll                                          = 21                       // constant.int64Val
	SmCxhthumb                                           = 10                       // constant.int64Val
	SmCxicon                                             = 11                       // constant.int64Val
	SmCxiconspacing                                      = 38                       // constant.int64Val
	SmCxmaximized                                        = 61                       // constant.int64Val
	SmCxmaxtrack                                         = 59                       // constant.int64Val
	SmCxmenucheck                                        = 71                       // constant.int64Val
	SmCxmenusize                                         = 54                       // constant.int64Val
	SmCxmin                                              = 28                       // constant.int64Val
	SmCxminimized                                        = 57                       // constant.int64Val
	SmCxminspacing                                       = 47                       // constant.int64Val
	SmCxmintrack                                         = 34                       // constant.int64Val
	SmCxpaddedborder                                     = 92                       // constant.int64Val
	SmCxscreen                                           = 0                        // constant.int64Val
	SmCxsize                                             = 30                       // constant.int64Val
	SmCxsizeframe                                        = 32                       // constant.int64Val
	SmCxsmicon                                           = 49                       // constant.int64Val
	SmCxsmsize                                           = 52                       // constant.int64Val
	SmCxvirtualscreen                                    = 78                       // constant.int64Val
	SmCxvscroll                                          = 2                        // constant.int64Val
	SmCyborder                                           = 6                        // constant.int64Val
	SmCycaption                                          = 4                        // constant.int64Val
	SmCycursor                                           = 14                       // constant.int64Val
	SmCydlgframe                                         = 8                        // constant.int64Val
	SmCydoubleclk                                        = 37                       // constant.int64Val
	SmCydrag                                             = 69                       // constant.int64Val
	SmCyedge                                             = 46                       // constant.int64Val
	SmCyfixedframe                                       = 8                        // constant.int64Val
	SmCyfocusborder                                      = 84                       // constant.int64Val
	SmCyframe                                            = 33                       // constant.int64Val
	SmCyfullscreen                                       = 17                       // constant.int64Val
	SmCyhscroll                                          = 3                        // constant.int64Val
	SmCyicon                                             = 12                       // constant.int64Val
	SmCyiconspacing                                      = 39                       // constant.int64Val
	SmCykanjiwindow                                      = 18                       // constant.int64Val
	SmCymaximized                                        = 62                       // constant.int64Val
	SmCymaxtrack                                         = 60                       // constant.int64Val
	SmCymenu                                             = 15                       // constant.int64Val
	SmCymenucheck                                        = 72                       // constant.int64Val
	SmCymenusize                                         = 55                       // constant.int64Val
	SmCymin                                              = 29                       // constant.int64Val
	SmCyminimized                                        = 58                       // constant.int64Val
	SmCyminspacing                                       = 48                       // constant.int64Val
	SmCymintrack                                         = 35                       // constant.int64Val
	SmCyscreen                                           = 1                        // constant.int64Val
	SmCysize                                             = 31                       // constant.int64Val
	SmCysizeframe                                        = 33                       // constant.int64Val
	SmCysmcaption                                        = 51                       // constant.int64Val
	SmCysmicon                                           = 50                       // constant.int64Val
	SmCysmsize                                           = 53                       // constant.int64Val
	SmCyvirtualscreen                                    = 79                       // constant.int64Val
	SmCyvscroll                                          = 20                       // constant.int64Val
	SmCyvthumb                                           = 9                        // constant.int64Val
	SmDbcsenabled                                        = 42                       // constant.int64Val
	SmDebug                                              = 22                       // constant.int64Val
	SmDigitizer                                          = 94                       // constant.int64Val
	SmImmenabled                                         = 82                       // constant.int64Val
	SmMaximumtouches                                     = 95                       // constant.int64Val
	SmMediacenter                                        = 87                       // constant.int64Val
	SmMenudropalignment                                  = 40                       // constant.int64Val
	SmMideastenabled                                     = 74                       // constant.int64Val
	SmMousehorizontalwheelpresent                        = 91                       // constant.int64Val
	SmMousepresent                                       = 19                       // constant.int64Val
	SmMousewheelpresent                                  = 75                       // constant.int64Val
	SmNetwork                                            = 63                       // constant.int64Val
	SmPenwindows                                         = 41                       // constant.int64Val
	SmRemotecontrol                                      = 8193                     // constant.int64Val
	SmRemotesession                                      = 4096                     // constant.int64Val
	SmReserved1                                          = 24                       // constant.int64Val
	SmReserved2                                          = 25                       // constant.int64Val
	SmReserved3                                          = 26                       // constant.int64Val
	SmReserved4                                          = 27                       // constant.int64Val
	SmSamedisplayformat                                  = 81                       // constant.int64Val
	SmSecure                                             = 44                       // constant.int64Val
	SmServerr2                                           = 89                       // constant.int64Val
	SmShowsounds                                         = 70                       // constant.int64Val
	SmShuttingdown                                       = 8192                     // constant.int64Val
	SmSlowmachine                                        = 73                       // constant.int64Val
	SmStarter                                            = 88                       // constant.int64Val
	SmSwapbutton                                         = 23                       // constant.int64Val
	SmTabletpc                                           = 86                       // constant.int64Val
	SmXvirtualscreen                                     = 76                       // constant.int64Val
	SmYvirtualscreen                                     = 77                       // constant.int64Val
	SwErase                                              = 4                        // constant.int64Val
	SwForceminimize                                      = 11                       // constant.int64Val
	SwHide                                               = 0                        // constant.int64Val
	SwInvalidate                                         = 2                        // constant.int64Val
	SwMax                                                = 11                       // constant.int64Val
	SwMaximize                                           = 3                        // constant.int64Val
	SwMinimize                                           = 6                        // constant.int64Val
	SwNormal                                             = 1                        // constant.int64Val
	SwOtherunzoom                                        = 4                        // constant.int64Val
	SwOtherzoom                                          = 2                        // constant.int64Val
	SwParentclosing                                      = 1                        // constant.int64Val
	SwParentopening                                      = 3                        // constant.int64Val
	SwRestore                                            = 9                        // constant.int64Val
	SwScrollchildren                                     = 1                        // constant.int64Val
	SwShow                                               = 5                        // constant.int64Val
	SwShowdefault                                        = 10                       // constant.int64Val
	SwShowmaximized                                      = 3                        // constant.int64Val
	SwShowminimized                                      = 2                        // constant.int64Val
	SwShowminnoactive                                    = 7                        // constant.int64Val
	SwShowna                                             = 8                        // constant.int64Val
	SwShownoactivate                                     = 4                        // constant.int64Val
	SwShownormal                                         = 1                        // constant.int64Val
	SwSmoothscroll                                       = 16                       // constant.int64Val
	SwpAsyncwindowpos                                    = 16384                    // constant.int64Val
	SwpDefererase                                        = 8192                     // constant.int64Val
	SwpDrawframe                                         = 32                       // constant.int64Val
	SwpFramechanged                                      = 32                       // constant.int64Val
	SwpHidewindow                                        = 128                      // constant.int64Val
	SwpNoactivate                                        = 16                       // constant.int64Val
	SwpNocopybits                                        = 256                      // constant.int64Val
	SwpNomove                                            = 2                        // constant.int64Val
	SwpNoownerzorder                                     = 512                      // constant.int64Val
	SwpNoredraw                                          = 8                        // constant.int64Val
	SwpNoreposition                                      = 512                      // constant.int64Val
	SwpNosendchanging                                    = 1024                     // constant.int64Val
	SwpNosize                                            = 1                        // constant.int64Val
	SwpNozorder                                          = 4                        // constant.int64Val
	SwpShowwindow                                        = 64                       // constant.int64Val
	SymbolCharset                                        = 2                        // constant.int64Val
	ThaiCharset                                          = 222                      // constant.int64Val
	TmeCancel                                            = 2147483648               // constant.int64Val
	TmeHover                                             = 1                        // constant.int64Val
	TmeLeave                                             = 2                        // constant.int64Val
	TmeNonclient                                         = 16                       // constant.int64Val
	TmeQuery                                             = 1073741824               // constant.int64Val
	True                                                 = 1                        // constant.int64Val
	TurkishCharset                                       = 162                      // constant.int64Val
	VariablePitch                                        = 2                        // constant.int64Val
	VietnameseCharset                                    = 163                      // constant.int64Val
	VkAccept                                             = 30                       // constant.int64Val
	VkAdd                                                = 107                      // constant.int64Val
	VkApps                                               = 93                       // constant.int64Val
	VkAttn                                               = 246                      // constant.int64Val
	VkBack                                               = 8                        // constant.int64Val
	VkBrowserBack                                        = 166                      // constant.int64Val
	VkBrowserFavorites                                   = 171                      // constant.int64Val
	VkBrowserForward                                     = 167                      // constant.int64Val
	VkBrowserHome                                        = 172                      // constant.int64Val
	VkBrowserRefresh                                     = 168                      // constant.int64Val
	VkBrowserSearch                                      = 170                      // constant.int64Val
	VkBrowserStop                                        = 169                      // constant.int64Val
	VkCancel                                             = 3                        // constant.int64Val
	VkCapital                                            = 20                       // constant.int64Val
	VkClear                                              = 12                       // constant.int64Val
	VkControl                                            = 17                       // constant.int64Val
	VkConvert                                            = 28                       // constant.int64Val
	VkCrsel                                              = 247                      // constant.int64Val
	VkDecimal                                            = 110                      // constant.int64Val
	VkDelete                                             = 46                       // constant.int64Val
	VkDivide                                             = 111                      // constant.int64Val
	VkDown                                               = 40                       // constant.int64Val
	VkEnd                                                = 35                       // constant.int64Val
	VkEreof                                              = 249                      // constant.int64Val
	VkEscape                                             = 27                       // constant.int64Val
	VkExecute                                            = 43                       // constant.int64Val
	VkExsel                                              = 248                      // constant.int64Val
	VkF1                                                 = 112                      // constant.int64Val
	VkF10                                                = 121                      // constant.int64Val
	VkF11                                                = 122                      // constant.int64Val
	VkF12                                                = 123                      // constant.int64Val
	VkF13                                                = 124                      // constant.int64Val
	VkF14                                                = 125                      // constant.int64Val
	VkF15                                                = 126                      // constant.int64Val
	VkF16                                                = 127                      // constant.int64Val
	VkF17                                                = 128                      // constant.int64Val
	VkF18                                                = 129                      // constant.int64Val
	VkF19                                                = 130                      // constant.int64Val
	VkF2                                                 = 113                      // constant.int64Val
	VkF20                                                = 131                      // constant.int64Val
	VkF21                                                = 132                      // constant.int64Val
	VkF22                                                = 133                      // constant.int64Val
	VkF23                                                = 134                      // constant.int64Val
	VkF24                                                = 135                      // constant.int64Val
	VkF3                                                 = 114                      // constant.int64Val
	VkF4                                                 = 115                      // constant.int64Val
	VkF5                                                 = 116                      // constant.int64Val
	VkF6                                                 = 117                      // constant.int64Val
	VkF7                                                 = 118                      // constant.int64Val
	VkF8                                                 = 119                      // constant.int64Val
	VkF9                                                 = 120                      // constant.int64Val
	VkFinal                                              = 24                       // constant.int64Val
	VkHangeul                                            = 21                       // constant.int64Val
	VkHangul                                             = 21                       // constant.int64Val
	VkHanja                                              = 25                       // constant.int64Val
	VkHelp                                               = 47                       // constant.int64Val
	VkHome                                               = 36                       // constant.int64Val
	VkIco00                                              = 228                      // constant.int64Val
	VkIcoClear                                           = 230                      // constant.int64Val
	VkIcoHelp                                            = 227                      // constant.int64Val
	VkInsert                                             = 45                       // constant.int64Val
	VkJunja                                              = 23                       // constant.int64Val
	VkKana                                               = 21                       // constant.int64Val
	VkKanji                                              = 25                       // constant.int64Val
	VkLaunchApp1                                         = 182                      // constant.int64Val
	VkLaunchApp2                                         = 183                      // constant.int64Val
	VkLaunchMail                                         = 180                      // constant.int64Val
	VkLaunchMediaSelect                                  = 181                      // constant.int64Val
	VkLbutton                                            = 1                        // constant.int64Val
	VkLcontrol                                           = 162                      // constant.int64Val
	VkLeft                                               = 37                       // constant.int64Val
	VkLmenu                                              = 164                      // constant.int64Val
	VkLshift                                             = 160                      // constant.int64Val
	VkLwin                                               = 91                       // constant.int64Val
	VkMbutton                                            = 4                        // constant.int64Val
	VkMediaNextTrack                                     = 176                      // constant.int64Val
	VkMediaPlayPause                                     = 179                      // constant.int64Val
	VkMediaPrevTrack                                     = 177                      // constant.int64Val
	VkMediaStop                                          = 178                      // constant.int64Val
	VkMenu                                               = 18                       // constant.int64Val
	VkModechange                                         = 31                       // constant.int64Val
	VkMultiply                                           = 106                      // constant.int64Val
	VkNext                                               = 34                       // constant.int64Val
	VkNoname                                             = 252                      // constant.int64Val
	VkNonconvert                                         = 29                       // constant.int64Val
	VkNumlock                                            = 144                      // constant.int64Val
	VkNumpad0                                            = 96                       // constant.int64Val
	VkNumpad1                                            = 97                       // constant.int64Val
	VkNumpad2                                            = 98                       // constant.int64Val
	VkNumpad3                                            = 99                       // constant.int64Val
	VkNumpad4                                            = 100                      // constant.int64Val
	VkNumpad5                                            = 101                      // constant.int64Val
	VkNumpad6                                            = 102                      // constant.int64Val
	VkNumpad7                                            = 103                      // constant.int64Val
	VkNumpad8                                            = 104                      // constant.int64Val
	VkNumpad9                                            = 105                      // constant.int64Val
	VkOem1                                               = 186                      // constant.int64Val
	VkOem102                                             = 226                      // constant.int64Val
	VkOem2                                               = 191                      // constant.int64Val
	VkOem3                                               = 192                      // constant.int64Val
	VkOem4                                               = 219                      // constant.int64Val
	VkOem5                                               = 220                      // constant.int64Val
	VkOem6                                               = 221                      // constant.int64Val
	VkOem7                                               = 222                      // constant.int64Val
	VkOem8                                               = 223                      // constant.int64Val
	VkOemAttn                                            = 240                      // constant.int64Val
	VkOemAuto                                            = 243                      // constant.int64Val
	VkOemAx                                              = 225                      // constant.int64Val
	VkOemBacktab                                         = 245                      // constant.int64Val
	VkOemClear                                           = 254                      // constant.int64Val
	VkOemComma                                           = 188                      // constant.int64Val
	VkOemCopy                                            = 242                      // constant.int64Val
	VkOemCusel                                           = 239                      // constant.int64Val
	VkOemEnlw                                            = 244                      // constant.int64Val
	VkOemFinish                                          = 241                      // constant.int64Val
	VkOemFjJisho                                         = 146                      // constant.int64Val
	VkOemFjLoya                                          = 149                      // constant.int64Val
	VkOemFjMasshou                                       = 147                      // constant.int64Val
	VkOemFjRoya                                          = 150                      // constant.int64Val
	VkOemFjTouroku                                       = 148                      // constant.int64Val
	VkOemJump                                            = 234                      // constant.int64Val
	VkOemMinus                                           = 189                      // constant.int64Val
	VkOemNecEqual                                        = 146                      // constant.int64Val
	VkOemPa1                                             = 235                      // constant.int64Val
	VkOemPa2                                             = 236                      // constant.int64Val
	VkOemPa3                                             = 237                      // constant.int64Val
	VkOemPeriod                                          = 190                      // constant.int64Val
	VkOemPlus                                            = 187                      // constant.int64Val
	VkOemReset                                           = 233                      // constant.int64Val
	VkOemWsctrl                                          = 238                      // constant.int64Val
	VkPa1                                                = 253                      // constant.int64Val
	VkPacket                                             = 231                      // constant.int64Val
	VkPause                                              = 19                       // constant.int64Val
	VkPlay                                               = 250                      // constant.int64Val
	VkPrint                                              = 42                       // constant.int64Val
	VkPrior                                              = 33                       // constant.int64Val
	VkProcesskey                                         = 229                      // constant.int64Val
	VkRbutton                                            = 2                        // constant.int64Val
	VkRcontrol                                           = 163                      // constant.int64Val
	VkReturn                                             = 13                       // constant.int64Val
	VkRight                                              = 39                       // constant.int64Val
	VkRmenu                                              = 165                      // constant.int64Val
	VkRshift                                             = 161                      // constant.int64Val
	VkRwin                                               = 92                       // constant.int64Val
	VkScroll                                             = 145                      // constant.int64Val
	VkSelect                                             = 41                       // constant.int64Val
	VkSeparator                                          = 108                      // constant.int64Val
	VkShift                                              = 16                       // constant.int64Val
	VkSleep                                              = 95                       // constant.int64Val
	VkSnapshot                                           = 44                       // constant.int64Val
	VkSpace                                              = 32                       // constant.int64Val
	VkSubtract                                           = 109                      // constant.int64Val
	VkTab                                                = 9                        // constant.int64Val
	VkUp                                                 = 38                       // constant.int64Val
	VkVolumeDown                                         = 174                      // constant.int64Val
	VkVolumeMute                                         = 173                      // constant.int64Val
	VkVolumeUp                                           = 175                      // constant.int64Val
	VkXbutton1                                           = 5                        // constant.int64Val
	VkXbutton2                                           = 6                        // constant.int64Val
	VkZoom                                               = 251                      // constant.int64Val
	WaActive                                             = 1                        // constant.int64Val
	WaClickactive                                        = 2                        // constant.int64Val
	WaInactive                                           = 0                        // constant.int64Val
	WmActivate                       MessageId           = 6
	WmActivateapp                    MessageId           = 28
	WmAfxfirst                       MessageId           = 864
	WmAfxlast                        MessageId           = 895
	WmApp                            MessageId           = 32768
	WmAppcommand                     MessageId           = 793
	WmAskcbformatname                MessageId           = 780
	WmCanceljournal                  MessageId           = 75
	WmCancelmode                     MessageId           = 31
	WmCapturechanged                 MessageId           = 533
	WmChangecbchain                  MessageId           = 781
	WmChangeuistate                  MessageId           = 295
	WmChar                           MessageId           = 258
	WmChartoitem                     MessageId           = 47
	WmChildactivate                  MessageId           = 34
	WmClear                          MessageId           = 771
	WmClipboardupdate                MessageId           = 797
	WmClose                          MessageId           = 16
	WmCommand                        MessageId           = 273
	WmCommnotify                     MessageId           = 68
	WmCompacting                     MessageId           = 65
	WmCompareitem                    MessageId           = 57
	WmContextmenu                    MessageId           = 123
	WmCopy                           MessageId           = 769
	WmCopydata                       MessageId           = 74
	WmCreate                         MessageId           = 1
	WmCtlcolorbtn                    MessageId           = 309
	WmCtlcolordlg                    MessageId           = 310
	WmCtlcoloredit                   MessageId           = 307
	WmCtlcolorlistbox                MessageId           = 308
	WmCtlcolormsgbox                 MessageId           = 306
	WmCtlcolorscrollbar              MessageId           = 311
	WmCtlcolorstatic                 MessageId           = 312
	WmCut                            MessageId           = 768
	WmDeadchar                       MessageId           = 259
	WmDeleteitem                     MessageId           = 45
	WmDestroy                        MessageId           = 2
	WmDestroyclipboard               MessageId           = 775
	WmDevicechange                   MessageId           = 537
	WmDevmodechange                  MessageId           = 27
	WmDisplaychange                  MessageId           = 126
	WmDpichanged                     MessageId           = 736
	WmDrawclipboard                  MessageId           = 776
	WmDrawitem                       MessageId           = 43
	WmDropfiles                      MessageId           = 563
	WmDwmcolorizationcolorchanged    MessageId           = 800
	WmDwmcompositionchanged          MessageId           = 798
	WmDwmncrenderingchanged          MessageId           = 799
	WmDwmsendiconiclivepreviewbitmap MessageId           = 806
	WmDwmsendiconicthumbnail         MessageId           = 803
	WmDwmwindowmaximizedchange       MessageId           = 801
	WmEnable                         MessageId           = 10
	WmEndsession                     MessageId           = 22
	WmEnteridle                      MessageId           = 289
	WmEntermenuloop                  MessageId           = 529
	WmEntersizemove                  MessageId           = 561
	WmErasebkgnd                     MessageId           = 20
	WmExitmenuloop                   MessageId           = 530
	WmExitsizemove                   MessageId           = 562
	WmFontchange                     MessageId           = 29
	WmGesture                        MessageId           = 281
	WmGesturenotify                  MessageId           = 282
	WmGetdlgcode                     MessageId           = 135
	WmGetfont                        MessageId           = 49
	WmGethotkey                      MessageId           = 51
	WmGeticon                        MessageId           = 127
	WmGetminmaxinfo                  MessageId           = 36
	WmGetobject                      MessageId           = 61
	WmGettext                        MessageId           = 13
	WmGettextlength                  MessageId           = 14
	WmGettitlebarinfoex              MessageId           = 831
	WmHandheldfirst                  MessageId           = 856
	WmHandheldlast                   MessageId           = 863
	WmHelp                           MessageId           = 83
	WmHotkey                         MessageId           = 786
	WmHscroll                        MessageId           = 276
	WmHscrollclipboard               MessageId           = 782
	WmIconerasebkgnd                 MessageId           = 39
	WmImeChar                        MessageId           = 646
	WmImeComposition                 MessageId           = 271
	WmImeCompositionfull             MessageId           = 644
	WmImeControl                     MessageId           = 643
	WmImeEndcomposition              MessageId           = 270
	WmImeKeydown                     MessageId           = 656
	WmImeKeylast                     MessageId           = 271
	WmImeKeyup                       MessageId           = 657
	WmImeNotify                      MessageId           = 642
	WmImeRequest                     MessageId           = 648
	WmImeSelect                      MessageId           = 645
	WmImeSetcontext                  MessageId           = 641
	WmImeStartcomposition            MessageId           = 269
	WmInitdialog                     MessageId           = 272
	WmInitmenu                       MessageId           = 278
	WmInitmenupopup                  MessageId           = 279
	WmInput                          MessageId           = 255
	WmInputDeviceChange              MessageId           = 254
	WmInputlangchange                MessageId           = 81
	WmInputlangchangerequest         MessageId           = 80
	WmKeydown                        MessageId           = 256
	WmKeyfirst                       MessageId           = 256
	WmKeylast                        MessageId           = 265
	WmKeyup                          MessageId           = 257
	WmKillfocus                      MessageId           = 8
	WmLbuttondblclk                  MessageId           = 515
	WmLbuttondown                    MessageId           = 513
	WmLbuttonup                      MessageId           = 514
	WmMbuttondblclk                  MessageId           = 521
	WmMbuttondown                    MessageId           = 519
	WmMbuttonup                      MessageId           = 520
	WmMdiactivate                    MessageId           = 546
	WmMdicascade                     MessageId           = 551
	WmMdicreate                      MessageId           = 544
	WmMdidestroy                     MessageId           = 545
	WmMdigetactive                   MessageId           = 553
	WmMdiiconarrange                 MessageId           = 552
	WmMdimaximize                    MessageId           = 549
	WmMdinext                        MessageId           = 548
	WmMdirefreshmenu                 MessageId           = 564
	WmMdirestore                     MessageId           = 547
	WmMdisetmenu                     MessageId           = 560
	WmMditile                        MessageId           = 550
	WmMeasureitem                    MessageId           = 44
	WmMenuchar                       MessageId           = 288
	WmMenucommand                    MessageId           = 294
	WmMenudrag                       MessageId           = 291
	WmMenugetobject                  MessageId           = 292
	WmMenurbuttonup                  MessageId           = 290
	WmMenuselect                     MessageId           = 287
	WmMouseactivate                  MessageId           = 33
	WmMousefirst                     MessageId           = 512
	WmMousehover                     MessageId           = 673
	WmMousehwheel                    MessageId           = 526
	WmMouselast                      MessageId           = 526
	WmMouseleave                     MessageId           = 675
	WmMousemove                      MessageId           = 512
	WmMousewheel                     MessageId           = 522
	WmMove                           MessageId           = 3
	WmMoving                         MessageId           = 534
	WmNcactivate                     MessageId           = 134
	WmNccalcsize                     MessageId           = 131
	WmNccreate                       MessageId           = 129
	WmNcdestroy                      MessageId           = 130
	WmNchittest                      MessageId           = 132
	WmNclbuttondblclk                MessageId           = 163
	WmNclbuttondown                  MessageId           = 161
	WmNclbuttonup                    MessageId           = 162
	WmNcmbuttondblclk                MessageId           = 169
	WmNcmbuttondown                  MessageId           = 167
	WmNcmbuttonup                    MessageId           = 168
	WmNcmousehover                   MessageId           = 672
	WmNcmouseleave                   MessageId           = 674
	WmNcmousemove                    MessageId           = 160
	WmNcpaint                        MessageId           = 133
	WmNcrbuttondblclk                MessageId           = 166
	WmNcrbuttondown                  MessageId           = 164
	WmNcrbuttonup                    MessageId           = 165
	WmNcxbuttondblclk                MessageId           = 173
	WmNcxbuttondown                  MessageId           = 171
	WmNcxbuttonup                    MessageId           = 172
	WmNextdlgctl                     MessageId           = 40
	WmNextmenu                       MessageId           = 531
	WmNotify                         MessageId           = 78
	WmNotifyformat                   MessageId           = 85
	WmNull                           MessageId           = 0
	WmPaint                          MessageId           = 15
	WmPaintclipboard                 MessageId           = 777
	WmPainticon                      MessageId           = 38
	WmPalettechanged                 MessageId           = 785
	WmPaletteischanging              MessageId           = 784
	WmParentnotify                   MessageId           = 528
	WmPaste                          MessageId           = 770
	WmPenwinfirst                    MessageId           = 896
	WmPenwinlast                     MessageId           = 911
	WmPower                          MessageId           = 72
	WmPowerbroadcast                 MessageId           = 536
	WmPrint                          MessageId           = 791
	WmPrintclient                    MessageId           = 792
	WmQuerydragicon                  MessageId           = 55
	WmQueryendsession                MessageId           = 17
	WmQuerynewpalette                MessageId           = 783
	WmQueryopen                      MessageId           = 19
	WmQueryuistate                   MessageId           = 297
	WmQueuesync                      MessageId           = 35
	WmQuit                           MessageId           = 18
	WmRbuttondblclk                  MessageId           = 518
	WmRbuttondown                    MessageId           = 516
	WmRbuttonup                      MessageId           = 517
	WmRenderallformats               MessageId           = 774
	WmRenderformat                   MessageId           = 773
	WmSetcursor                      MessageId           = 32
	WmSetfocus                       MessageId           = 7
	WmSetfont                        MessageId           = 48
	WmSethotkey                      MessageId           = 50
	WmSeticon                        MessageId           = 128
	WmSetredraw                      MessageId           = 11
	WmSettext                        MessageId           = 12
	WmSettingchange                  MessageId           = 26
	WmShowwindow                     MessageId           = 24
	WmSize                           MessageId           = 5
	WmSizeclipboard                  MessageId           = 779
	WmSizing                         MessageId           = 532
	WmSpoolerstatus                  MessageId           = 42
	WmStylechanged                   MessageId           = 125
	WmStylechanging                  MessageId           = 124
	WmSyncpaint                      MessageId           = 136
	WmSyschar                        MessageId           = 262
	WmSyscolorchange                 MessageId           = 21
	WmSyscommand                     MessageId           = 274
	WmSysdeadchar                    MessageId           = 263
	WmSyskeydown                     MessageId           = 260
	WmSyskeyup                       MessageId           = 261
	WmTabletFirst                    MessageId           = 704
	WmTabletLast                     MessageId           = 735
	WmTcard                          MessageId           = 82
	WmThemechanged                   MessageId           = 794
	WmTimechange                     MessageId           = 30
	WmTimer                          MessageId           = 275
	WmTouch                          MessageId           = 576
	WmUndo                           MessageId           = 772
	WmUnichar                        MessageId           = 265
	WmUninitmenupopup                MessageId           = 293
	WmUpdateuistate                  MessageId           = 296
	WmUser                           MessageId           = 1024
	WmUserchanged                    MessageId           = 84
	WmVkeytoitem                     MessageId           = 46
	WmVscroll                        MessageId           = 277
	WmVscrollclipboard               MessageId           = 778
	WmWindowposchanged               MessageId           = 71
	WmWindowposchanging              MessageId           = 70
	WmWininichange                   MessageId           = 26
	WmWtssessionChange               MessageId           = 689
	WmXbuttondblclk                  MessageId           = 525
	WmXbuttondown                    MessageId           = 523
	WmXbuttonup                      MessageId           = 524
	WsActivecaption                                      = 1          // constant.int64Val
	WsBorder                                             = 8388608    // constant.int64Val
	WsCaption                                            = 12582912   // constant.int64Val
	WsChild                                              = 1073741824 // constant.int64Val
	WsChildwindow                                        = 1073741824 // constant.int64Val
	WsClipchildren                                       = 33554432   // constant.int64Val
	WsClipsiblings                                       = 67108864   // constant.int64Val
	WsDisabled                                           = 134217728  // constant.int64Val
	WsDlgframe                                           = 4194304    // constant.int64Val
	WsExAcceptfiles                                      = 16         // constant.int64Val
	WsExAppwindow                                        = 262144     // constant.int64Val
	WsExClientedge                                       = 512        // constant.int64Val
	WsExComposited                                       = 33554432   // constant.int64Val
	WsExContexthelp                                      = 1024       // constant.int64Val
	WsExControlparent                                    = 65536      // constant.int64Val
	WsExDlgmodalframe                                    = 1          // constant.int64Val
	WsExLayered                                          = 524288     // constant.int64Val
	WsExLayoutrtl                                        = 4194304    // constant.int64Val
	WsExLeft                                             = 0          // constant.int64Val
	WsExLeftscrollbar                                    = 16384      // constant.int64Val
	WsExLtrreading                                       = 0          // constant.int64Val
	WsExMdichild                                         = 64         // constant.int64Val
	WsExNoactivate                                       = 134217728  // constant.int64Val
	WsExNoinheritlayout                                  = 1048576    // constant.int64Val
	WsExNoparentnotify                                   = 4          // constant.int64Val
	WsExOverlappedwindow                                 = 768        // constant.int64Val
	WsExPalettewindow                                    = 392        // constant.int64Val
	WsExRight                                            = 4096       // constant.int64Val
	WsExRightscrollbar                                   = 0          // constant.int64Val
	WsExRtlreading                                       = 8192       // constant.int64Val
	WsExStaticedge                                       = 131072     // constant.int64Val
	WsExToolwindow                                       = 128        // constant.int64Val
	WsExTopmost                                          = 8          // constant.int64Val
	WsExTransparent                                      = 32         // constant.int64Val
	WsExWindowedge                                       = 256        // constant.int64Val
	WsGroup                                              = 131072     // constant.int64Val
	WsHscroll                                            = 1048576    // constant.int64Val
	WsIconic                                             = 536870912  // constant.int64Val
	WsMaximize                                           = 16777216   // constant.int64Val
	WsMaximizebox                                        = 65536      // constant.int64Val
	WsMinimize                                           = 536870912  // constant.int64Val
	WsMinimizebox                                        = 131072     // constant.int64Val
	WsOverlapped                                         = 0          // constant.int64Val
	WsOverlappedwindow                                   = 13565952   // constant.int64Val
	WsPopup                                              = 2147483648 // constant.int64Val
	WsPopupwindow                                        = 2156396544 // constant.int64Val
	WsSizebox                                            = 262144     // constant.int64Val
	WsSysmenu                                            = 524288     // constant.int64Val
	WsTabstop                                            = 65536      // constant.int64Val
	WsThickframe                                         = 262144     // constant.int64Val
	WsTiled                                              = 0          // constant.int64Val
	WsTiledwindow                                        = 13565952   // constant.int64Val
	WsVisible                                            = 268435456  // constant.int64Val
	WsVscroll                                            = 2097152    // constant.int64Val
)
